"""Compiler-backed source ownership model."""

from .index import (
    SourceAbi,
    SourceBaseOffset,
    SourceBaseVtable,
    DeclarationKey,
    SourceClass,
    SourceCollector,
    SourceDeclaration,
    SourceField,
    SourceIndex,
    SourceIndexError,
    SourceMemberUse,
    SourceArrayIndex,
    SourceConversion,
    SourceMarker,
    ResolvedField,
    TranslationUnitRecords,
    keyed,
    record_command,
)
from .variables import SourceConflict, SourceConflictVariant, SourceVariable

__all__ = [
    "DeclarationKey",
    "keyed",
    "SourceAbi",
    "SourceBaseOffset",
    "SourceBaseVtable",
    "SourceClass",
    "SourceCollector",
    "SourceConflict",
    "SourceConflictVariant",
    "SourceDeclaration",
    "SourceField",
    "SourceIndex",
    "SourceIndexError",
    "SourceMemberUse",
    "SourceArrayIndex",
    "SourceConversion",
    "SourceMarker",
    "ResolvedField",
    "SourceVariable",
    "TranslationUnitRecords",
    "record_command",
]
