name: Format

on: [push, pull_request]

jobs:
  python-format:
    name: 'Python Format'
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: '3.15'

    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

    - uses: actions/setup-python@v7
      with:
        python-version: '3.15'
        allow-prereleases: true

    - name: Install python libraries
      shell: bash
      id: install
      run: |
        uv sync --locked --group dev

    - name: Run black
      if: ${{ always() && steps.install.outcome == 'success' }}
      shell: bash
      run: uv run --locked --group dev black --check .

    - name: Run pylint
      if: ${{ always() && steps.install.outcome == 'success' }}
      shell: bash
      run: uv run --locked --group dev pylint reccmp tests

    - name: Run mypy
      if: ${{ always() && steps.install.outcome == 'success' }}
      shell: bash
      run: uv run --locked --group dev mypy ./reccmp ./tests

    - name: Run codespell
      if: ${{ always() && steps.install.outcome == 'success' }}
      shell: bash
      run: |
        uv run --locked --group dev codespell \
          --ignore-multiline-regex \
            '# codespell:ignore-begin.*?codespell:ignore-end *\n' \
          --ignore-regex remote-checkin-comment \
          -L SEH \
          -S "./tests/cvdump_sample/*.txt" \
          ./reccmp ./tests
