name: Install

on: [push, pull_request]

jobs:
  install:
    name: 'Test reccmp install'
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

    - uses: actions/setup-python@v7
      with:
        python-version: '3.12'

    - name: Install reccmp
      shell: bash
      run: |
        uv sync --locked && uv run --locked reccmp-reccmp --help