name: Test with Ghidra

on: [push, pull_request]

jobs:
  test:
    name: 'Ghidra integration tests'
    runs-on: 'ubuntu-latest'

    container:
      # Note: This version should be kept in sync with ghidra-stubs in pyproject.toml
      image: blacktop/ghidra:12.1.2
      env:
        # not set by default for some reason
        GHIDRA_INSTALL_DIR: '/ghidra'

    steps:
    - uses: actions/checkout@v7

    # We cannot reuse the fetch-deps step from the other unit tests because the cache is not shared if different
    # container images are used, see https://github.com/actions/cache/issues/1361#issuecomment-2611294058
    - name: Restore original binaries
      id: cache
      uses: actions/cache@v6
      with:
        path: binfiles
        key: legobin

    - name: Download original island binaries
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: |
        wget https://legoisland.org/download/ISLE.EXE --directory-prefix=binfiles

    - name: Verify files
      run: |
        echo "5cf57c284973fce9d14f5677a2e4435fd989c5e938970764d00c8932ed5128ca binfiles/ISLE.EXE" | sha256sum --check

    # Install manually because the install action does not work inside this container
    - name: Install uv and project deps
      shell: bash
      run: |
        apt-get update
        apt-get -y install curl ca-certificates build-essential
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="$HOME/.local/bin:$PATH"
        uv sync --locked --group test

    - name: Run unit tests
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        uv run pytest . --binfiles=binfiles --require-ghidra
